#!/bin/bash

# MySQL 변수 정의
DB_NAME="webdb"
TABLE_NAME="members"
DB_USER="webuser"
USER_PWD="password"

# SQL 명령어 정의
SQL_COMMANDS=$(cat <<EOF
CREATE DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${USER_PWD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
USE ${DB_NAME};
CREATE TABLE ${TABLE_NAME} (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
EOF
)

# MySQL 접속 및 실행
mysql -uroot -e "${SQL_COMMANDS}"
